version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticketing_postgres
    restart: always
    environment:
      POSTGRES_USER: engine_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: ticketing_engine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing_network

  redis:
    image: redis:7-alpine
    container_name: ticketing_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ticketing_network
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ticketing_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: engine_admin
      RABBITMQ_DEFAULT_PASS: supersecretpassword
    ports:
      - "5672:5672"   # The actual port Node.js uses to send messages
      - "15672:15672" # The Web UI Dashboard port
    networks:
      - ticketing_network

networks:
  ticketing_network:
    driver: bridge

volumes:
  postgres_data: